# Generated by Django 3.2.8 on 2021-10-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('units_shipping', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=11)),
                ('is_admin', models.BooleanField()),
            ],
        ),
    ]
