# Generated by Django 3.2.8 on 2021-10-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='is_admin',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='providers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='providers',
            name='units_shipping',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
