# Generated by Django 3.2.8 on 2021-10-11 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='Head_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(default='Mercatodo', max_length=11)),
                ('address', models.CharField(default='Address', max_length=100)),
                ('dispatch_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.body_orders')),
                ('head_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.head_orders')),
            ],
        ),
    ]
