# Generated by Django 3.2.8 on 2021-10-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
